; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{7C4E1A2B-9D63-4F18-A6E5-2B8C0D4E91F7}
AppName=NewYoutubeDownloader
AppVersion=0.1
AppVerName=NewYoutubeDownloader 0.1
AppPublisher=NewYoutubeDownloader
AppPublisherURL=
AppSupportURL=
AppUpdatesURL=
DefaultDirName={commonpf}\NewYoutubeDownloader
DefaultGroupName=NewYoutubeDownloader
AllowNoIcons=yes
OutputDir=D:\Inno output\0.1
OutputBaseFilename=NewYoutubeDownloader
SetupIconFile=..\YoutubePlaylistDownloader\finalIcon.ico
Compression=lzma
SolidCompression=yes
UninstallDisplayIcon=..\YoutubePlaylistDownloader\finalIcon.ico

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "hebrew"; MessagesFile: "compiler:Languages\Hebrew.isl"
Name: "chinese"; MessagesFile: "ChineseSimplified.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}";

[Files]
Source: "..\YoutubePlaylistDownloader\bin\Release\net8.0-windows\*"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\bin\bin32\ffmpeg.exe"; DestDir: "{app}"; Flags: ignoreversion

; NOTE: Don't use "Flags: ignoreversion" on any shared system files        

[Icons]
Name: "{group}\NewYoutubeDownloader"; Filename: "{app}\NewYoutubeDownloader.exe"
Name: "{commondesktop}\NewYoutubeDownloader"; Filename: "{app}\NewYoutubeDownloader.exe"; Tasks: desktopicon

[Run]
Filename: "{app}\NewYoutubeDownloader.exe"; Description: "{cm:LaunchProgram,NewYoutubeDownloader}"; Flags: nowait postinstall skipifsilent

